void* TransactWithClient(void *);
void ServerSignalHandler();
void CleanExit(void*);
int DatabaseConnect();
void SocketConnect(char*[]);
int Command(const char *, ...);
void SigHandler(int);
void RequestMonitor(int);
void ViewMonitoringStatus(int);
void Exit();
int CheckStatus(char*);
void StartMonitor(int*);
int FileExists(char*,int);
